### ISSUE TITLE
 the issue： assert block_filtering is False AssertionError，hope for your help please!  

### ISSUE THREAD

**Issue by Baser-Bai** [pangsu0613/CLOCs#51]
'''$ python train.py train --config_path=second/configs/car.fhd.config --model_dir=mymodel'''

          
      '''    /home/vci-1/anaconda3/envs/BR_CLOCs/lib/python3.7/site-packages/numba/cuda/decorators.py:110: NumbaDeprecationWarning: Eager compilation of device functions is deprecated (this occurs when a signature is provided)
            warn(NumbaDeprecationWarning(msg))
          /home/vci-1/anaconda3/envs/BR_CLOCs/lib/python3.7/site-packages/numba/cuda/decorators.py:110: NumbaDeprecationWarning: Eager compilation of device functions is deprecated (this occurs when a signature is provided)
            warn(NumbaDeprecationWarning(msg))
          /home/vci-1/anaconda3/envs/BR_CLOCs/lib/python3.7/site-packages/numba/cuda/decorators.py:110: NumbaDeprecationWarning: Eager compilation of device functions is deprecated (this occurs when a signature is provided)
            warn(NumbaDeprecationWarning(msg))
          /home/vci-1/anaconda3/envs/BR_CLOCs/lib/python3.7/site-packages/numba/cuda/decorators.py:110: NumbaDeprecationWarning: Eager compilation of device functions is deprecated (this occurs when a signature is provided)
            warn(NumbaDeprecationWarning(msg))
          /home/vci-1/anaconda3/envs/BR_CLOCs/lib/python3.7/site-packages/numba/cuda/decorators.py:110: NumbaDeprecationWarning: Eager compilation of device functions is deprecated (this occurs when a signature is provided)
            warn(NumbaDeprecationWarning(msg))
          /home/vci-1/anaconda3/envs/BR_CLOCs/lib/python3.7/site-packages/numba/cuda/decorators.py:110: NumbaDeprecationWarning: Eager compilation of device functions is deprecated (this occurs when a signature is provided)
            warn(NumbaDeprecationWarning(msg))
          /home/vci-1/anaconda3/envs/BR_CLOCs/lib/python3.7/site-packages/numba/cuda/decorators.py:110: NumbaDeprecationWarning: Eager compilation of device functions is deprecated (this occurs when a signature is provided)
            warn(NumbaDeprecationWarning(msg))
          /home/vci-1/anaconda3/envs/BR_CLOCs/lib/python3.7/site-packages/numba/cuda/decorators.py:110: NumbaDeprecationWarning: Eager compilation of device functions is deprecated (this occurs when a signature is provided)
            warn(NumbaDeprecationWarning(msg))
          /home/vci-1/anaconda3/envs/BR_CLOCs/lib/python3.7/site-packages/numba/cuda/decorators.py:110: NumbaDeprecationWarning: Eager compilation of device functions is deprecated (this occurs when a signature is provided)
            warn(NumbaDeprecationWarning(msg))
          /home/vci-1/anaconda3/envs/BR_CLOCs/lib/python3.7/site-packages/numba/cuda/decorators.py:110: NumbaDeprecationWarning: Eager compilation of device functions is deprecated (this occurs when a signature is provided)
            warn(NumbaDeprecationWarning(msg))
          /home/vci-1/anaconda3/envs/BR_CLOCs/lib/python3.7/site-packages/numba/cuda/decorators.py:110: NumbaDeprecationWarning: Eager compilation of device functions is deprecated (this occurs when a signature is provided)
            warn(NumbaDeprecationWarning(msg))
          /home/vci-1/anaconda3/envs/BR_CLOCs/lib/python3.7/site-packages/numba/cuda/decorators.py:110: NumbaDeprecationWarning: Eager compilation of device functions is deprecated (this occurs when a signature is provided)
            warn(NumbaDeprecationWarning(msg))
          2d detection path: ../d2_detection_data
          sparse_shape: [  41 1600 1408]
          num_class is : 1
          load existing model
          Restoring parameters from mymodel/adam_optimizer-0.tckpt
          {'Car': 5}
          [-1]
          load 14357 Car database infos
          load 2207 Pedestrian database infos
          load 734 Cyclist database infos
          load 1297 Van database infos
          load 56 Person_sitting database infos
          load 488 Truck database infos
          load 224 Tram database infos
          load 337 Misc database infos
          After filter database:
          load 10520 Car database infos
          load 2104 Pedestrian database infos
          load 594 Cyclist database infos
          load 826 Van database infos
          load 53 Person_sitting database infos
          load 321 Truck database infos
          load 199 Tram database infos
          load 259 Misc database infos
          remain number of infos: 3712
          remain number of infos: 3769
          WORKER 0 seed: 1637719420
          WORKER 1 seed: 1637719421
          WORKER 2 seed: 1637719422
          Traceback (most recent call last):
            File "train.py", line 925, in <module>
              fire.Fire()
            File "/home/vci-1/anaconda3/envs/BR_CLOCs/lib/python3.7/site-packages/fire/core.py", line 141, in Fire
              component_trace = _Fire(component, args, parsed_flag_args, context, name)
            File "/home/vci-1/anaconda3/envs/BR_CLOCs/lib/python3.7/site-packages/fire/core.py", line 471, in _Fire
              target=component.__name__)
            File "/home/vci-1/anaconda3/envs/BR_CLOCs/lib/python3.7/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
              component = fn(*varargs, **kwargs)
            File "train.py", line 378, in train
              raise e
            File "train.py", line 238, in train
              example = next(data_iter)
            File "/home/vci-1/anaconda3/envs/BR_CLOCs/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
              data = self._next_data()
            File "/home/vci-1/anaconda3/envs/BR_CLOCs/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
              return self._process_data(data)
            File "/home/vci-1/anaconda3/envs/BR_CLOCs/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
              data.reraise()
            File "/home/vci-1/anaconda3/envs/BR_CLOCs/lib/python3.7/site-packages/torch/_utils.py", line 429, in reraise
              raise self.exc_type(msg)
          AssertionError: Caught AssertionError in DataLoader worker process 0.
          Original Traceback (most recent call last):
            File "/home/vci-1/anaconda3/envs/BR_CLOCs/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
              data = fetcher.fetch(index)
            File "/home/vci-1/anaconda3/envs/BR_CLOCs/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
              data = [self.dataset[idx] for idx in possibly_batched_index]
            File "/home/vci-1/anaconda3/envs/BR_CLOCs/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
              data = [self.dataset[idx] for idx in possibly_batched_index]
            File "/home/vci-1/BR/FUSION_CAM_LADAR/CLOCs-master/second/pytorch/builder/input_reader_builder.py", line 18, in __getitem__
              return self._dataset[idx]
            File "/home/vci-1/BR/FUSION_CAM_LADAR/CLOCs-master/second/data/dataset.py", line 70, in __getitem__
              prep_func=self._prep_func)
            File "/home/vci-1/BR/FUSION_CAM_LADAR/CLOCs-master/second/data/preprocess.py", line 363, in _read_and_prep_v9
              example = prep_func(input_dict=input_dict)
            File "/home/vci-1/BR/FUSION_CAM_LADAR/CLOCs-master/second/data/preprocess.py", line 225, in prep_pointcloud
              points, max_voxels)
            File "/home/vci-1/anaconda3/envs/BR_CLOCs/lib/python3.7/site-packages/spconv/utils/__init__.py", line 173, in generate
              or self._max_voxels, self._full_mean)
            File "/home/vci-1/anaconda3/envs/BR_CLOCs/lib/python3.7/site-packages/spconv/utils/__init__.py", line 69, in points_to_voxel
              assert block_filtering is False
          AssertionError'''

**Comment by Baser-Bai** [comment]
this project need spconv1.0. but my bag is spconv1.1.when install spconv1.0, this problem is not exist.
